version: 1.0.{build}
init:
- cmd: 'echo Python: %PYTHON%'
environment:
  PYTHON: C:\Python35-x64
install:
- cmd: '%PYTHON%/Scripts/pip.exe install codecov'
before_build:
- cmd: nuget restore
build:
  project: ScintillaNET-Kitchen.sln
  verbosity: normal
after_test:
- cmd: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\Tests\bin\Debug\ScintillaNET-KitchenTest.dll" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\ScintillaNET-KitchenTest_coverage.xml


    %PYTHON%/Scripts/codecov.exe -f "ScintillaNET-KitchenTest_coverage.xml"